
  default: &default
    adapter: postgresql
    encoding: utf8
    database: calltracker
    # username: hading
    # password: my_db_password
    host: localhost # not mandatory
    pool: 5 # not mandatory
    timeout: 5000 # not mandatory

  development:
    adapter: postgresql
    encoding: utf8
    database: calltracker
    # username: hading
    # password: my_db_password
    host: localhost # not mandatory
    pool: 5 # not mandatory
    timeout: 5000 # not mandatory

  test:
    adapter: postgresql
    encoding: utf8
    database: calltracker
    # username: hading
    # password: my_db_password
    host: localhost # not mandatory
    pool: 5 # not mandatory
    timeout: 5000 # not mandatory

  production:
    adapter: postgresql
    encoding: utf8
    database: calltracker
    # username: hading
    # password: my_db_password
    host: localhost # not mandatory
    pool: 5 # not mandatory
    timeout: 5000 # not mandatory
